### PR TITLE
normalize path to unix-style directory separator,…

### LINKED ISSUE #13: a editorconfig with windows CRLF is not properly parsed
it seems the class is not able to parse a simple editor.config file, when it contains CRLF instead of LF.

is this intentionally not supported? is editorconfig per defintion a LF ending format?

we are running into trouble because git sometimes auto-converts line endings and thefore the files do no longer work after checkout on some machines.

would it be possible to support CRLF ending files?

### PR DESCRIPTION
**Pull request by staabm**
…because the [glob pattern assumes linux-style directory separators](https://github.com/idiosyncratic-code/editorconfig-php/blob/50f742daee8b7a632b795f5927d8d88c43dd3a4f/src/EditorConfigFile.php#L134)

closes https://github.com/idiosyncratic-code/editorconfig-php/issues/13

### CODE REVIEW

**Comment by staabm** [comment]
just verified, that the unit test fails without the patch and passes when included.

the patch also fixes another test, which currently fails on windows:

```
1) Idiosyncratic\EditorConfig\EditorConfigFileTest::testGetConfigForPath with data set "This .php file has an indentation of 4" ('C:\dvl\GitHub\editorconfig-ph...st.php', 4)
Undefined array key "indent_size"
```

**Comment by staabm** [comment]
ping @jcsilkey

**Comment by jcsilkey** [comment]
Hi @staabm,

Conceptually this looks fine, once CI checks pass I'll merge.

**Comment by staabm** [comment]
thx for setting up the CI pipeline, really appreciate that!

I fixed the build on linux and this should be good to go now. thanks!

the CI is waiting for a manuel trigger to get started - github actions new bitcoin mining prevention - which is used because I never contributed to this project before :()

**Comment by jcsilkey** [comment]
@staabm Bitcoin really does ruin everything...

I approved it to run, looks like there's still one more error. 

It took me longer than expected to get around to setting up the CI as this is a side project for me and other things have kept me from giving it the attention it deserves. Now that it's set up though it should make it faster to get things merged since now I don't have to check the things the robots can check. I'm also going to setup running the tests on windows since I don't use it myself and typically don't check everything on there (VMs are such a pain).

**Comment by staabm** [comment]
Args - fixed CS

**Pull request merged**
